CREATE TABLE "statistics_preferences" (
  "user_id" TEXT NOT NULL,
  "breakeven_percent" DECIMAL(8,4) NOT NULL DEFAULT 0.1,
  "time_zone" TEXT NOT NULL DEFAULT 'Asia/Seoul',
  "trading_day_start_minutes" INTEGER NOT NULL DEFAULT 120,
  "asia_start_minutes" INTEGER NOT NULL DEFAULT 540,
  "asia_end_minutes" INTEGER NOT NULL DEFAULT 960,
  "london_start_minutes" INTEGER NOT NULL DEFAULT 480,
  "london_end_minutes" INTEGER NOT NULL DEFAULT 1020,
  "new_york_start_minutes" INTEGER NOT NULL DEFAULT 480,
  "new_york_end_minutes" INTEGER NOT NULL DEFAULT 1020,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "statistics_preferences_pkey" PRIMARY KEY ("user_id"),
  CONSTRAINT "statistics_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app_users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "statistics_preferences_breakeven_percent_check" CHECK ("breakeven_percent" >= 0 AND "breakeven_percent" <= 100),
  CONSTRAINT "statistics_preferences_trading_day_start_check" CHECK ("trading_day_start_minutes" BETWEEN 0 AND 1439),
  CONSTRAINT "statistics_preferences_asia_start_check" CHECK ("asia_start_minutes" BETWEEN 0 AND 1439),
  CONSTRAINT "statistics_preferences_asia_end_check" CHECK ("asia_end_minutes" BETWEEN 0 AND 1439),
  CONSTRAINT "statistics_preferences_london_start_check" CHECK ("london_start_minutes" BETWEEN 0 AND 1439),
  CONSTRAINT "statistics_preferences_london_end_check" CHECK ("london_end_minutes" BETWEEN 0 AND 1439),
  CONSTRAINT "statistics_preferences_new_york_start_check" CHECK ("new_york_start_minutes" BETWEEN 0 AND 1439),
  CONSTRAINT "statistics_preferences_new_york_end_check" CHECK ("new_york_end_minutes" BETWEEN 0 AND 1439)
);
