import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { TradeStatsPreferences, TradeStatsResponse } from '@trading-journal/shared';
import { StatsPage } from './StatsPage';
afterEach(() => { cleanup(); localStorage.clear(); });
const preferences: TradeStatsPreferences = { breakevenPercent: 0.1, timeZone: 'America/New_York', tradingDayStartMinutes: 0, sessions: { asia: { startMinutes: 0, endMinutes: 480 }, london: { startMinutes: 480, endMinutes: 960 }, 'new-york': { startMinutes: 780, endMinutes: 1260 } }, display: { timeZone: 'Asia/Seoul', utcOffsetMinutes: 540, tradingDayStartLabel: '09:00', sessions: { asia: { startLabel: '09:00', endLabel: '17:00' }, london: { startLabel: '17:00', endLabel: '01:00' }, 'new-york': { startLabel: '22:00', endLabel: '06:00' } } } };
const bucket = { key: 'EURUSD', label: 'EURUSD', count: 12, classifiedCount: 12, winRate: 50, realizedPnl: 120, oneLotPnl: 60, sufficiency: '10-29' as const };
const overview = { totalTrades: 12, totalRealizedPnl: 120, averageRealizedPnl: 10, oneLotPnl: 60, winRate: 50, breakevenRate: 5, profitFactor: 1.4, payoff: 1.2, expectancy: 10, wins: 6, losses: 5, breakevens: 1, classifiedCount: 12, averageWin: 30, averageLoss: -15, maxWinStreak: 3, currentWinStreak: 2, maxLossStreak: 2, currentLossStreak: 0, totalRiskAmount: 20, riskAmountCount: 10, riskPercentCount: 10, r: { value: 1, count: 8, missingCount: 4, total: 8, expectancy: 1 } };
const series = { granularity: 'day' as const, points: [{ key: '2026-01-01', label: '1월 1일', count: 1, realizedPnl: 120, equity: 120, winRate: 50 }], activeBucketAverage: 120, calendarBucketAverage: 60 };
const cell = { ...bucket, key: 'london', label: 'London', predicates: [{ dimension: 'symbol' as const, key: 'breakout' }, { dimension: 'session' as const, key: 'london' }] };
const stats: TradeStatsResponse = { preferences, query: { accountId: 'a', unit: 'campaign' }, overview, comparison: { current: overview, prior: overview, from: '2026-01-01', to: '2026-01-02', priorFrom: '2025-12-30', priorTo: '2025-12-31' }, timeSeries: { sequence: { ...series, granularity: 'sequence', points: [{ ...series.points[0], key: '1', label: '매매 1' }] }, day: series, week: { ...series, granularity: 'week' }, month: { ...series, granularity: 'month' }, year: { ...series, granularity: 'year' } }, breakdowns: { symbol: [bucket] }, crosstab: { rowDimension: 'symbol', columnDimension: 'session', columns: [{ key: 'asia', label: 'Asia', predicate: { dimension: 'session', key: 'asia' } }, { key: 'london', label: 'London', predicate: { dimension: 'session', key: 'london' } }], rows: [{ key: 'breakout', label: 'Breakout', predicate: { dimension: 'symbol', key: 'breakout' }, cells: [cell] }] }, drawdown: { money: 20, percent: 2, r: 1 }, distributions: [{ metric: 'realizedPnl', bins: [{ key: '0-100', min: 0, max: 100, count: 4 }] }, { metric: 'oneLotPnl', bins: [] }, { metric: 'r', bins: [] }], diagnostics: { missingSeedCount: 1, missingSeedIds: ['seed-1'], unclassifiedCount: 0, missingLotsCount: 1, missingLotsIds: ['lots-1'], missingRiskCount: 1, missingRiskIds: ['risk-1'], incompleteCampaignCount: 1, incompleteCampaignIds: ['campaign-1'] }, drilldown: [{ id: 'trade-1', targetId: 'campaign-9', type: 'campaign', tradeIds: ['trade-1'], campaignId: 'campaign-9', journalDate: '2026-01-03', accountId: 'a', symbol: 'EURUSD', side: 'long', openedAt: '2026-01-01T01:00:00Z', closedAt: '2026-01-01T02:00:00Z', realizedPnl: 120, lots: 1, outcome: 'win' }] };
function page(request = vi.fn((path: string) => Promise.resolve(path.includes('preferences') ? preferences : { ...stats, filterOptions: { symbol: [{ key: 'EURUSD', label: 'EURUSD' }], session: [{ key: 'new-york', label: 'new-york' }, { key: 'asia', label: 'asia' }], entryWeekday: [{ key: '금요일', label: '금요일' }, { key: '월요일', label: '월요일' }], exitReason: [{ key: 'manual', label: 'manual' }], baseTimeframe: [{ key: '1h', label: '1h' }] } }))) { const open = vi.fn(); render(<StatsPage accountId="a" request={request} onOpenRecord={open} />); return { request, open }; }
describe('StatsPage', () => {
  it('renders redesigned metrics, selected diagnostics and populated breakdown panels', async () => { page(); expect(await screen.findByText('연속 기록')).toBeInTheDocument(); expect(screen.getByText('위험 조정 성과')).toBeInTheDocument(); expect(screen.getByText('최대 낙폭 (MDD)')).toBeInTheDocument(); expect(screen.queryByText('기대 수익')).not.toBeInTheDocument(); expect(screen.getByText('PF (Profit Factor)')).toHaveAttribute('data-tooltip', expect.stringContaining('총 수익 PnL')); expect(screen.getByText('거래당 평균 포인트')).toHaveAttribute('data-tooltip', expect.stringContaining('각 매매에 1 Lot')); expect(screen.getAllByRole('alert').some((alert) => alert.textContent?.includes('seed-1'))).toBe(true); expect(screen.queryByText(/위험금액 누락\/주의/)).not.toBeInTheDocument(); expect(screen.queryByText(/미완성 캠페인 누락\/주의/)).not.toBeInTheDocument(); expect(screen.getByText('0 ~ 100')).toBeInTheDocument(); });
  it('uses 매매 and 진입 terminology and removes direction and outcome filters', async () => { page(); expect(await screen.findByRole('button', { name: '매매' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: '진입' })).toBeInTheDocument(); expect(screen.queryByLabelText('long')).not.toBeInTheDocument(); expect(screen.queryByLabelText('win')).not.toBeInTheDocument(); });
  it('shows entry-only filters only for entry statistics and localizes ordered options', async () => { const { request } = page(); fireEvent.click(await screen.findByRole('button', { name: '필터 열기' })); await screen.findByText('아시아장'); expect(screen.getByText('미장')).toBeInTheDocument(); expect(screen.getByText('월요일').compareDocumentPosition(screen.getByText('금요일')) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy(); expect(screen.queryByRole('group', { name: '청산 사유' })).not.toBeInTheDocument(); expect(screen.queryByRole('group', { name: '기준봉' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '진입' })); expect(await screen.findByRole('group', { name: '청산 사유' })).toBeInTheDocument(); expect(screen.getByRole('group', { name: '기준봉' })).toBeInTheDocument(); fireEvent.click(screen.getByLabelText('1h')); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('unit=trade') && path.includes('baseTimeframes=1h'))).toBe(true)); fireEvent.click(screen.getByRole('button', { name: '매매' })); await waitFor(() => { const path = request.mock.calls.at(-1)?.[0] ?? ''; expect(path).toContain('unit=campaign'); expect(path).not.toContain('baseTimeframes'); expect(path).not.toContain('exitReasons'); }); });
  it('renders global crosstab headers and aligned empty cells', async () => { page(); expect(await screen.findByRole('columnheader', { name: 'Asia' })).toBeInTheDocument(); expect(screen.getByRole('columnheader', { name: 'London' })).toBeInTheDocument(); expect(screen.getByText('—')).toBeInTheDocument(); });
  it('uses both crosstab predicates to refetch drilldown records', async () => { const { request } = page(); await screen.findByText('London'); fireEvent.click(screen.getByRole('button', { name: /120.*12건/ })); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('symbols=breakout') && path.includes('sessions=london'))).toBe(true)); });
  it('renders database filter options and applies checkbox selections', async () => { const { request } = page(); fireEvent.click(await screen.findByRole('button', { name: '필터 열기' })); const symbol = await screen.findByLabelText('EURUSD'); fireEvent.click(symbol); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('symbols=EURUSD'))).toBe(true)); });
  it('defaults to the first trade through the current Seoul date', async () => { const { request } = page(); await screen.findByRole('button', { name: '매매' }); expect(screen.getByLabelText('시작일')).toHaveValue('2026-01-03'); expect(screen.getByLabelText('종료일')).toBeDisabled(); expect(screen.getByLabelText('오늘')).toBeChecked(); expect(screen.queryByText('전문 통계')).not.toBeInTheDocument(); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('from=2026-01-03') && path.includes('to='))).toBe(true)); });
  it('opens the canonical drilldown record identity for journal navigation', async () => { const { open } = page(); await screen.findAllByRole('button', { name: 'EURUSD' }); fireEvent.click(screen.getAllByRole('button', { name: 'EURUSD' }).at(-1)!); expect(open).toHaveBeenCalledWith(expect.objectContaining({ targetId: 'campaign-9', journalDate: '2026-01-03' })); });
  it('restores cached unit and dates while refreshing a checked today date', async () => { localStorage.setItem('sentra:stats-controls', JSON.stringify({ unit: 'trade', from: '2026-02-01', to: '2020-01-01', throughLatest: true })); const { request } = page(); await waitFor(() => expect(screen.getByRole('button', { name: '진입' })).toHaveClass('active')); expect(screen.getByLabelText('시작일')).toHaveValue('2026-02-01'); expect(screen.getByLabelText('종료일')).not.toHaveValue('2020-01-01'); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('unit=trade') && path.includes('from=2026-02-01') && !path.includes('to=2020-01-01'))).toBe(true)); });
  it('caches detailed selections and clears them with reset', async () => { localStorage.setItem('sentra:stats-filters-open', 'true'); localStorage.setItem('sentra:stats-controls', JSON.stringify({ unit: 'campaign', throughLatest: true, filters: { from: '2026-01-03', symbols: ['EURUSD'] } })); page(); await waitFor(() => expect(screen.getByLabelText('EURUSD')).toBeChecked()); fireEvent.click(screen.getByRole('button', { name: '필터 초기화' })); expect(screen.getByLabelText('EURUSD')).not.toBeChecked(); expect(screen.getByRole('button', { name: '매매' })).toHaveClass('active'); });
  it('recalculates statistics without changing filters', async () => { const { request } = page(); await screen.findByRole('button', { name: '다시 계산' }); const calls = request.mock.calls.length; fireEvent.click(screen.getByRole('button', { name: '다시 계산' })); await waitFor(() => expect(request.mock.calls.length).toBeGreaterThan(calls)); });
  it('keeps filters hidden by default and caches visibility', async () => { page(); expect(await screen.findByRole('button', { name: '필터 열기' })).toHaveAttribute('aria-expanded', 'false'); expect(screen.queryByLabelText('상세 조회 조건')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '필터 열기' })); expect(await screen.findByLabelText('상세 조회 조건')).toBeInTheDocument(); expect(localStorage.getItem('sentra:stats-filters-open')).toBe('true'); });
  it('renders TradingView PnL and win-rate charts with campaign sequence granularity', async () => { page(); expect(await screen.findByRole('img', { name: '누적 실현 PnL TradingView 추이' })).toBeInTheDocument(); expect(screen.getByRole('img', { name: '누적 승률 TradingView 추이' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('tab', { name: '매매' })); expect(screen.getAllByRole('img').length).toBeGreaterThanOrEqual(2); });
});
