import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { TradeStatsPreferences, TradeStatsResponse } from '@trading-journal/shared';
import { StatsPage } from './StatsPage';
afterEach(cleanup);
const preferences: TradeStatsPreferences = { breakevenPercent: 0.1, timeZone: 'America/New_York', tradingDayStartMinutes: 0, sessions: { asia: { startMinutes: 0, endMinutes: 480 }, london: { startMinutes: 480, endMinutes: 960 }, 'new-york': { startMinutes: 780, endMinutes: 1260 } }, display: { timeZone: 'Asia/Seoul', utcOffsetMinutes: 540, tradingDayStartLabel: '09:00', sessions: { asia: { startLabel: '09:00', endLabel: '17:00' }, london: { startLabel: '17:00', endLabel: '01:00' }, 'new-york': { startLabel: '22:00', endLabel: '06:00' } } } };
const bucket = { key: 'EURUSD', label: 'EURUSD', count: 12, classifiedCount: 12, winRate: 50, realizedPnl: 120, oneLotPnl: 60, sufficiency: '10-29' as const };
const overview = { totalTrades: 12, totalRealizedPnl: 120, averageRealizedPnl: 10, oneLotPnl: 60, winRate: 50, breakevenRate: 5, profitFactor: 1.4, payoff: 1.2, expectancy: 10, wins: 6, losses: 5, breakevens: 1, classifiedCount: 12, averageWin: 30, averageLoss: -15, maxWinStreak: 3, currentWinStreak: 2, maxLossStreak: 2, currentLossStreak: 0, totalRiskAmount: 20, riskAmountCount: 10, riskPercentCount: 10, r: { value: 1, count: 8, missingCount: 4, total: 8, expectancy: 1 } };
const series = { granularity: 'day' as const, points: [{ key: '2026-01-01', label: '1월 1일', count: 1, realizedPnl: 120, equity: 120 }], activeBucketAverage: 120, calendarBucketAverage: 60 };
const cell = { ...bucket, key: 'london', label: 'London', predicates: [{ dimension: 'strategy' as const, key: 'breakout' }, { dimension: 'session' as const, key: 'london' }] };
const stats: TradeStatsResponse = { preferences, query: { accountId: 'a', unit: 'campaign' }, overview, comparison: { current: overview, prior: overview, from: '2026-01-01', to: '2026-01-02', priorFrom: '2025-12-30', priorTo: '2025-12-31' }, timeSeries: { day: series, week: { ...series, granularity: 'week' }, month: { ...series, granularity: 'month' }, year: { ...series, granularity: 'year' } }, breakdowns: { symbol: [bucket], strategy: [{ ...bucket, key: 'breakout', label: 'Breakout' }] }, crosstab: { rowDimension: 'strategy', columnDimension: 'session', columns: [{ key: 'asia', label: 'Asia', predicate: { dimension: 'session', key: 'asia' } }, { key: 'london', label: 'London', predicate: { dimension: 'session', key: 'london' } }], rows: [{ key: 'breakout', label: 'Breakout', predicate: { dimension: 'strategy', key: 'breakout' }, cells: [cell] }] }, drawdown: { money: 20, percent: 2, r: 1 }, distributions: [{ metric: 'realizedPnl', bins: [{ key: '0-100', min: 0, max: 100, count: 4 }] }, { metric: 'oneLotPnl', bins: [] }, { metric: 'r', bins: [] }], diagnostics: { missingSeedCount: 1, missingSeedIds: ['seed-1'], unclassifiedCount: 0, missingLotsCount: 1, missingLotsIds: ['lots-1'], missingRiskCount: 1, missingRiskIds: ['risk-1'], incompleteCampaignCount: 1, incompleteCampaignIds: ['campaign-1'] }, drilldown: [{ id: 'trade-1', targetId: 'campaign-9', type: 'campaign', tradeIds: ['trade-1'], campaignId: 'campaign-9', journalDate: '2026-01-03', accountId: 'a', symbol: 'EURUSD', side: 'long', openedAt: '2026-01-01T01:00:00Z', closedAt: '2026-01-01T02:00:00Z', realizedPnl: 120, lots: 1, outcome: 'win' }] };
function page(request = vi.fn((path: string) => Promise.resolve(path.includes('preferences') ? preferences : stats))) { const open = vi.fn(); render(<StatsPage accountId="a" request={request} onOpenRecord={open} />); return { request, open }; }
describe('StatsPage', () => {
  it('renders metrics, diagnostics and only populated breakdown panels', async () => { page(); expect(await screen.findByText('연속 승 / 패')).toBeInTheDocument(); expect(screen.getByText('총 / 평균 / 기대 R')).toBeInTheDocument(); expect(screen.getAllByRole('alert').some((alert) => alert.textContent?.includes('seed-1'))).toBe(true); expect(screen.getByText('0 ~ 100')).toBeInTheDocument(); expect(screen.queryByText('oneLotPnl 분포')).not.toBeInTheDocument(); });
  it('exposes side and outcome query filters', async () => { const { request } = page(); await screen.findByText('전문 통계'); fireEvent.click(screen.getByLabelText('long')); fireEvent.click(screen.getByLabelText('win')); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('sides=long') && path.includes('outcomes=win'))).toBe(true)); });
  it('renders global crosstab headers and aligned empty cells', async () => { page(); expect(await screen.findByRole('columnheader', { name: 'Asia' })).toBeInTheDocument(); expect(screen.getByRole('columnheader', { name: 'London' })).toBeInTheDocument(); expect(screen.getByText('—')).toBeInTheDocument(); });
  it('uses both crosstab predicates to refetch drilldown records', async () => { const { request } = page(); await screen.findByText('London'); fireEvent.click(screen.getByRole('button', { name: /120.*12건/ })); await waitFor(() => expect(request.mock.calls.some(([path]) => path.includes('strategies=breakout') && path.includes('sessions=london'))).toBe(true)); });
  it('saves an exact preference body, accepts UTC, and refetches stats', async () => { const { request } = page(); await screen.findByText('전문 통계'); fireEvent.change(screen.getByLabelText('분석 시간대'), { target: { value: 'UTC' } }); fireEvent.click(screen.getByRole('button', { name: '환경설정 저장' })); await waitFor(() => { const patch = request.mock.calls.find(([path, init]) => path === '/trade-log/stats/preferences' && init?.method === 'PATCH'); expect(patch).toBeTruthy(); expect(JSON.parse(patch![1]!.body as string)).toEqual({ breakevenPercent: 0.1, timeZone: 'UTC', tradingDayStartMinutes: 0, sessions: preferences.sessions }); expect(request.mock.calls.filter(([path]) => path.startsWith('/trade-log/stats?')).length).toBeGreaterThan(1); }); });
  it('opens the canonical drilldown record identity for journal navigation', async () => { const { open } = page(); await screen.findAllByRole('button', { name: 'EURUSD' }); fireEvent.click(screen.getAllByRole('button', { name: 'EURUSD' }).at(-1)!); expect(open).toHaveBeenCalledWith(expect.objectContaining({ targetId: 'campaign-9', journalDate: '2026-01-03' })); });
});
